// Per-hero voice clips sourced from deadlock.wiki/<Hero>/Quotes Select
// section. Generated by scripts/build-voicelines.mjs into
// data/voicelines.json. Sound mode uses these as the "what does this
// hero sound like" hint that unlocks late in the puzzle.

import data from "@/data/voicelines.json";

export type VoiceClip = {
  file: string;       // basename, e.g. "select-01.mp3"
  url: string;        // path under /public, e.g. "/voicelines/infernus/select-01.mp3"
  transcript: string; // what the hero says in the clip — used for a11y label only
  bytes: number;
};

export type HeroVoice = {
  prefix: string;     // wiki audio-file class code (Inferno, Gigawatt, …)
  clips: VoiceClip[];
};

export const VOICELINES: Record<string, HeroVoice> = data as Record<
  string,
  HeroVoice
>;

export function hasVoiceClips(heroKey: string): boolean {
  return !!VOICELINES[heroKey] && VOICELINES[heroKey].clips.length > 0;
}

// Deterministic clip pick — seed off the day + hero + line index so the
// same daily puzzle always plays the same clip per (speaker, line) pair,
// but distinct lines get distinct clips.
export function pickClip(
  heroKey: string,
  seed: number,
): VoiceClip | null {
  const v = VOICELINES[heroKey];
  if (!v || v.clips.length === 0) return null;
  return v.clips[seed % v.clips.length];
}
